### ISSUE TITLE
Widget not present when siteconfiguration from import

### ISSUE THREAD

**Issue by prathers** [brotkrueml/typo3-matomo-widgets#19]
We use a config.yaml for our site configuration which imports the settings from our EXT:my_sitepackage:
`imports:
  -
    resource: 'EXT:my_sitepackage/Configuration/Routes/Default.yaml'`

Trouble is that the Matomo Widgets only loads, if the settings are made directly in the confic/sites/site-name/config.yaml. If we load the matomo settings in EXT:my_sitepackage/Configuration/Routes/Default.yaml, no widgets are present.

```
matomoWidgetsActiveWidgets: 'actionsPerDay,actionsPerMonth,bounceRate,browserPlugins,browsers,campaigns,contentNames,contentPieces,countries,linkMatomo,osFamilies,siteSearchKeywords,siteSearchNoResultKeywords,visitsPerDay,visitsPerMonth'
matomoWidgetsIdSite: 1
matomoWidgetsTitle: 'DEMO'
matomoWidgetsTokenAuth: ''
matomoWidgetsUrl: 'https://demo.matomo.cloud/'
```

Cleared the BIG cache too :)

**Comment by brotkrueml** [comment]
Thanks for the report. Will have a look in the next days.

**Comment by brotkrueml** [comment]
@prathers A new version 1.0.2 is released which fixes this issue. Thanks for the report.

**Comment by prathers** [comment]
Worx! Thanks
