### ISSUE TITLE
Can't flush cache with extension installed in TYPO3 11

### ISSUE THREAD

**Issue by PhilippKuhlmay** [brotkrueml/typo3-matomo-widgets#20]
Hi I have TYPO3 11.4 with your extension in version 1.1.0 installed.
I now can not flush the cache. Neither in the backend, nor in the cli.

The cli says:
```
$ ddev typo3cms cache:flush

                                             
  [ Error ]                                  
  Call to a member function error() on null  
                                             
Exception trace:
#0 ()
   typo3/sysext/core/Classes/Configuration/Loader/YamlFileLoader.php:168
#1 TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader->processImports()
   typo3/sysext/core/Classes/Configuration/Loader/YamlFileLoader.php:93
#2 TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader->loadAndParse()
   typo3/sysext/core/Classes/Configuration/Loader/YamlFileLoader.php:69
#3 TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader->load()
   typo3conf/ext/matomo_widgets/Classes/Configuration/ConfigurationFinder.php:36
#4 Brotkrueml\MatomoWidgets\Configuration\ConfigurationFinder->__construct()
   typo3conf/ext/matomo_widgets/Configuration/Services.php:59
#5 Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader::{closure}()
   vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:149
#6 Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback()
   vendor/symfony/dependency-injection/Loader/PhpFileLoader.php:67
#7 Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load()
   typo3/sysext/core/Classes/DependencyInjection/ContainerBuilder.php:126
#8 TYPO3\CMS\Core\DependencyInjection\ContainerBuilder->buildContainer()
   typo3/sysext/core/Classes/DependencyInjection/ContainerBuilder.php:95
#9 TYPO3\CMS\Core\DependencyInjection\ContainerBuilder->createDependencyInjectionContainer()
   typo3/sysext/core/Classes/Core/BootService.php:59
#10 TYPO3\CMS\Core\Core\BootService->prepareContainer()
   typo3/sysext/core/Classes/Core/BootService.php:48
#11 TYPO3\CMS\Core\Core\BootService->getContainer()
   typo3/sysext/core/Classes/Command/CacheFlushCommand.php:73
#12 TYPO3\CMS\Core\Command\CacheFlushCommand->execute()
   vendor/symfony/console/Command/Command.php:299
#13 Symfony\Component\Console\Command\Command->run()
   vendor/symfony/console/Application.php:978
#14 Symfony\Component\Console\Application->doRunCommand()
   vendor/helhum/typo3-console/Classes/Console/Mvc/Cli/Symfony/Application.php:189
#15 Helhum\Typo3Console\Mvc\Cli\Symfony\Application->doRunCommand()
   vendor/symfony/console/Application.php:295
#16 Symfony\Component\Console\Application->doRun()
   vendor/symfony/console/Application.php:167
#17 Symfony\Component\Console\Application->run()
   vendor/helhum/typo3-console/Classes/Console/Core/Kernel.php:114
#18 Helhum\Typo3Console\Core\Kernel->handle()
   vendor/helhum/typo3-console/Scripts/typo3-console.php:31
#19 {closure}()
   vendor/helhum/typo3-console/Scripts/typo3-console.php:33
#20 require()
   vendor/helhum/typo3-console/typo3cms:3


Failed to run typo3cms cache:flush: exit status 1
```

I only occures with this extension installed. After removing it, it works.

**Comment by brotkrueml** [comment]
Hey Philipp,
thanks for the report. I can't reproduce it, neither with PHP 7.4 nor PHP 8.0 installed in my ddev project.
As I can see in the backtrace, the typo3-console is called. Please check, if typo3-console is installed in version 7.0. In this version the cache:flush command is not available anymore. Also call `ddev typo3 cache:flush` (mind the missing cms part) to use the TYPO3 core command.
Chris.

**Comment by PhilippKuhlmay** [comment]
Hi Chris,

typo3-console v7.0.1 is installed. It doesn't work with `ddev typo3 cache:flush`. Very strange is, that it works with other projects. But in the project where it doesn't work, I installed version v1.0.1 and now it works. Since version v1.0.2 it doesn't work.

It seems that your changes in `https://github.com/brotkrueml/typo3-matomo-widgets/blob/457673e8ae654baae7f55f9ca49354c6f8dfe229/Classes/Configuration/ConfigurationFinder.php#L35` crashes inside my installation.

Stack Trace inside TYPO3:

<img width="881" alt="Bildschirmfoto 2021-09-20 um 11 58 32" src="https://user-images.githubusercontent.com/57705869/133984821-2a22a1d2-de15-4775-bfd5-e70f4d458ed8.png">

**Comment by brotkrueml** [comment]
Ah, yes, the YamlFileLoader uses the LoggerAwareTrait, so that a logger is injected into the class via DI. I overlooked that, have to set a logger manually or create an instance of the YamlFileLoader via DI. Will take care.

**Comment by brotkrueml** [comment]
@PhilippKuhlmay Can you please check against master branch if the issue is solved? Seems like your installation throws an exception which will be logged, that's why the error occurred. Perhaps there is another issue in your installation.

**Comment by PhilippKuhlmay** [comment]
@brotkrueml It works now with dev-master
