### ISSUE TITLE
Update or new Installation with error from Version 1.0.2 - 1.1.2

### ISSUE THREAD

**Issue by heyse-dc** [brotkrueml/typo3-matomo-widgets#26]
Hello when I am updating or making a new installation via Extension Manager
TYPO3 Version: 10.4.21
1.0.1 Works
1.0.2 - 1.1.2 following Error occur:

YAML File "/html/typo3/typo3conf/sites/main/config.yaml" could not be loaded

Core: Exception handler (WEB):  Uncaught TYPO3 Exception: Class 'Brotkrueml\MatomoWidgets\Extension' not  found \| Error thrown in file  /html/typo3/typo3temp/var/cache/code/core/ext_tables_b8547d191b70d9187c1a11eb653862efd40bf8b7.php  in line 1484. Requested URL:  https://XXX.de/typo3/

Core: Error handler (BE): PHP Warning: include(): Failed opening '/home/www/XXX/html/typo3/typo3conf/ext/matomo_widgets/Classes/Extension.php' for inclusion (include_path='.:/usr/lib/mw/php/7.4/lib/php') in /html/typo3/typo3_src-10.4.21/vendor/composer/ClassLoader.php line 480 

Core: Error handler (BE): PHP Warning: include(/home/www/XXX/html/typo3/typo3conf/ext/matomo_widgets/Classes/Extension.php): failed to open stream: No such file or directory in /html/typo3/typo3_src-10.4.21/vendor/composer/ClassLoader.php line 480

**Comment by heyse-dc** [comment]
Its a classic Installation via Mittwald Kundencenter
There is no Classes/Extension.php in the Installation
I switched it to Master Version 1.2.0-dev and it works now. THX

**Comment by brotkrueml** [comment]
@heyse-dc Okay, will release a new version 1.2.0 planned for next week.

Related: #19, #20, #24
