### ISSUE TITLE
YAMLFileLoadingException after Update to v1.0.2

### ISSUE THREAD

**Issue by maslme** [brotkrueml/typo3-matomo-widgets#27]
### Current behavior

After Updating matomo_widgets to version 1.0.2 my whole installation breaks with  
#1485784246 TYPO3\CMS\Core\Configuration\Loader\Exception\YamlFileLoadingException

YAML File "/*/*/typo3conf/sites/***/config.yaml" could not be loaded

### Steps to reproduce

With matomo_widgets v1.0.1 or v1.0.0 no error occurs

### Environment

- Matomo Widgets version(s): 1.0.2
- TYPO3 version(s): 10.4.21
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: UNIX Server with PHP 7.3.10

**Comment by brotkrueml** [comment]
Please try current master, there it should be fixed.

Related: #26 
Related: #24 
Related: #20 
Related: #19
