### ISSUE TITLE
 Link to Matomo 

### ISSUE THREAD

**Issue by PatrickNetzDesign** [brotkrueml/typo3-matomo-widgets#33]
Currently the 'Link to Matomo' Widget has only a link to Matomo, without considering any extra parameters.

The problem behind this is, if a user has more than one dashboard to manage multiple pages, the user manual needs to change the page on Matomo. 

Would be great to have at least the parameter for the sideID such as ‘&idSite=3’. 
Also, to consider it would be perfect to be able to config additional parameters if needed such as ‘&date=yesterday’ and ‘&period=day’. 

It could be placed in the site configuration, like the other widgets.

**Comment by brotkrueml** [comment]
Thanks for your request. The site ID parameter can be added, that should be no big deal and is useful.

Regarding the additional parameters, just tried:
- I am already signed-in, and call my Matomo installation with idSite parameter and get the (from the user) configured date and period parameters (e.g. for me the current month)
- I am not signed-in, get the redirect page, sign-in and see the given idSite. But the parameters are default (e.g. for me now the previous day).

So, this is inconsistent from Matomo. I would expect that both variants display the view configured from the user. This should be fixed on Matomo site in my opinion to display always the configured view, independent if the user is already signed-in or has to take a redirect via the sign-in page. So please open an issue there: https://github.com/matomo-org/matomo

**Comment by PatrickNetzDesign** [comment]
Sounds great 👍 
Thank you, I will do :)

**Comment by brotkrueml** [comment]
So, only the idSite parameter would be nice ...
