### ISSUE TITLE
PHP 8.2 install:fixfolderstructure: PHP Fatal error:  Attribute "SensitiveParameter" cannot target property (allowed targets: parameter)

### ISSUE THREAD

**Issue by wrock** [brotkrueml/typo3-matomo-widgets#43]
### Current behavior

When calling 'php vendor/bin/typo3cms install:fixfolderstructure' the error occurs. Only with PHP 8.2, with PHP 8.1 the error does not occur.

### Expected behavior/output

Run without error

### Steps to reproduce

run command in cli:
php vendor/bin/typo3cms install:fixfolderstructure

### Environment

- Matomo Widgets version(s): 2.1.0
- TYPO3 version(s): 11.5.22
- PHP 8.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: ddev apache-fpm

**Comment by brotkrueml** [comment]
Hej @wrock , thanks for your report.

I cannot reproduce it on my ddev box:

```
php vendor/bin/typo3cms install:fixfolderstructure
The following directory structure has been fixed:
File /public/fileadmin/_temp_/.htaccess successfully created.
Set content to /public/fileadmin/_temp_/.htaccess
Fixed permission on /public/fileadmin/_temp_/.htaccess.
File /public/fileadmin/_temp_/index.html successfully created.
Set content to /public/fileadmin/_temp_/index.html
Fixed permission on /public/fileadmin/_temp_/index.html.
```

Environment:
```
php -v
PHP 8.2.0 (cli) (built: Dec  8 2022 15:03:15) (NTS)
```

I also checked the usage of the SensitiveParameters, but they are all implemented for parameters (not properties).

Are you sure the error is triggered from EXT:matomo_widgets?

**Comment by wrock** [comment]
Hi @brotkrueml, I cannot reproduce the error anymore - I'm very sorry for this false report. 2 days ago even after restarting ddev it occured... Pls close this issue.
