### ISSUE TITLE
Proxy configuration is not taken into account

### ISSUE THREAD

**Issue by FBuchholz** [brotkrueml/typo3-matomo-widgets#46]
### Current behavior

Dashboard is stopping typo3 an afters show attached error.

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1595862844: Content returned from Matomo Reporting API is not JSON encoded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> | Brotkrueml\MatomoWidgets\Exception\InvalidResponseException thrown in file /var/www/website/vendor/brotkrueml/typo3-matomo-widgets/Classes/Connection/MatomoConnector.php in line 64. Requested URL: https://www.   /typo3/ajax/dashboard/widget/content?token=--AnonymizedToken--&widget=matomo_widgets. .devicesDetection.osFamilies
```

### Expected behavior/output

Working Dashboard and not stopping typo3.

### Steps to reproduce

Configure dashboard in siteconfig.

### Screenshots
<img width="1622" alt="issue_matomo_wi" src="https://github.com/brotkrueml/typo3-matomo-widgets/assets/8975492/dc58150f-115f-43d2-8f16-8c2819435db5">

### Environment

TYPO3 Version | 12.4.1

nginx/1.25.0  PHP  8.2.6
MySQL 10.9.6-MariaDB-1:10.9.6+maria~ubu2204

Linux 5.15.0-73-generic 

- Matomo Widgets version(s):   v2.2.0

- TYPO3 version(s): 12.4.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: UBUNTU 22.04 

### Possible Solution

Proxy parameter not used by extension e.g. exclution local hosts?

**Comment by FBuchholz** [comment]
YES, the call has direct local Connection without Proxy. If no Proxy are Setup the Dashboards are Working as expected. The Issue is only with enabled Proxy Parameter inkl. excluded Hosts as attached in this Ticket.

**Comment by brotkrueml** [comment]
Okay, strange, as I just use the default client provided by TYPO3. Will look into it in the next days.

**Comment by brotkrueml** [comment]
@FBuchholz I created a fix: https://github.com/brotkrueml/typo3-matomo-widgets/commit/b0a253651be3ffcddaa7eaf33b87616d3e688eaa in the https://github.com/brotkrueml/typo3-matomo-widgets/commits/bugfix-46 branch. Please check and confirm, if this solves your issue.

**Comment by brotkrueml** [comment]
@FBuchholz Can you have a look at the fix and if it works for you? https://github.com/brotkrueml/typo3-matomo-widgets/commit/b0a253651be3ffcddaa7eaf33b87616d3e688eaa in the https://github.com/brotkrueml/typo3-matomo-widgets/commits/bugfix-46 branch

**Comment by brotkrueml** [comment]
@FBuchholz Sadly, it seems the feature is not important to you anymore. It won't get merged, if no feedback is provided. Please have a look at the PR.

**Comment by FBuchholz** [comment]
Hi, sorry for the delay. I tested the lib feature and can confirm that it works. 
KR
Frank
