### ISSUE TITLE
Add widget for most visited pages

### ISSUE THREAD

**Issue by stigfaerch** [brotkrueml/typo3-matomo-widgets#47]
### Is your feature request related to a problem? Please describe.

Our users would like to be able to see which pages currently are visited the most.

### Describe the solution you'd like

Something like:
Dashboard  > "Movers and Shakers"
![Screenshot 2023-06-30 at 08 15 22](https://github.com/brotkrueml/typo3-matomo-widgets/assets/6790776/5a18d4d8-e28a-48e3-b249-245435412a4a)

-> Request moved to #48.

and

Behavior > Pages
![Screenshot 2023-06-30 at 08 18 00](https://github.com/brotkrueml/typo3-matomo-widgets/assets/6790776/36a0a747-11e6-4d4f-9df4-7078a26714b4)

**Comment by brotkrueml** [comment]
@stigfaerch Thanks for the feature request. What exactly do you need? As far as I understand, you suggest two new dashboard widgets? If this is the case, please open also two issues, so they are separated.

Regarding the "Movers and Shakers": An example API call is:

    ?module=API&method=Insights.getMoversAndShakersOverview&idSite=1&period=month&date=today&format=JSON&token_auth=<token>&language=en

See: https://developer.matomo.org/api-reference/reporting-api#Insights

For the "Pages", what fields are necessary? Should they be configurable? Maybe multiple widgets are also an options (for page views, bounce rate, exit rate, ...)

**Comment by stigfaerch** [comment]
@brotkrueml 
Hi Chris
Forgot to keep track on this issue, but my project leader reminded me.
Thanks for splitting the feature request in to two separate issues.
We are still very much interested in both these features.

**Comment by brotkrueml** [comment]
@stigfaerch Will provide the first one (most viewed pages) in the next days, I assume. There is already a branch for this:
https://github.com/brotkrueml/typo3-matomo-widgets/tree/feature-47

**Comment by brotkrueml** [comment]
@stigfaerch The "Most viewed pages" is now complete. You can find it in the feature-47 branch. Feedback is welcome.

**Comment by stigfaerch** [comment]
@brotkrueml Many many thanks! I have now installed, and we will be testing in the coming days.

**Comment by stigfaerch** [comment]
@brotkrueml 
Seems to work as expected. But we believe it's essential for users to see which time period is associated with the statistic.
A nice to have would be that the user could actually choose the time period.

**Comment by brotkrueml** [comment]
This is far beyond the scope of this PR. This would need to reload the widget (and request the new data via API) based on some form values. I have no plans to implement that. But you can adjust the period in Services.yaml.

Remember: The widgets are just quick lookups for base metrics, not a replacement of the Matomo backend. For deeper inspections the Matomo backend should be used.

**Comment by stigfaerch** [comment]
@brotkrueml I understand. But we still think that the user at least should be able to decode which period of time the list represents. Could it be possible to add the text for explaining through configuration?

**Comment by brotkrueml** [comment]
@stigfaerch Yup, I agree, but this is also an issue of the already available widgets. Feel free to open an issue or provide a pull request. Currently, I have little time to contribute to my packages due to the amount of work in the documentation team - so don't expect something in the near future.
