### ISSUE TITLE
Configurable description text for widgets

### ISSUE THREAD

**Issue by stigfaerch** [brotkrueml/typo3-matomo-widgets#50]
### Is your feature request related to a problem? Please describe.

For some widgets, it can be hard to know for the user what the widget precisely shows. For example the "Most viewed pages", is in some sense self-explanatory, but still user wouldn't know if it shows all-time most viewed or if it's the last week, month or year.

### Describe the solution you'd like

Would be nice, if you could optional configure a explanatory description text for any widget.

**Comment by brotkrueml** [comment]
Current implementation:

![Bildschirmfoto vom 2024-01-22 14-04-22](https://github.com/brotkrueml/typo3-matomo-widgets/assets/2566282/ff4dd05c-542c-4d28-9cd3-3205d07087f5)

Will most likely not shipped with version 2.x but with version 3.0. The reason is: I would like to use symfony/clock package which is available in TYPO3 v12+, but not in TYPO3 v11. It is needed for adding time-based unit tests in an easy way.

**Comment by brotkrueml** [comment]
Will postpone it eventually to a later release. It is not that trivial, for example, have to check what should be displayed, for example:

- period: day / date: lastWeek
- period: day / date: lastMonth
- period: week / date: lastMonth
- period: week / date: lastWeek

I assume, that day/lastMonth displays the numbers for the same day on the last month. day/lastWeek displays the numbers of the same weekday for the last week. And what should week/lastMonth or week/lastWeek display? I am getting some numbers, but for which period? Have to dig into the Matomo code, I assume.

First priority is to release a v13-compatible version of the extension.

**Comment by stigfaerch** [comment]
@brotkrueml
A temporary solution, could be that the description text is just an optional static text that you define in the configuration?

**Comment by brotkrueml** [comment]
Hmm, then the user has to adjust the description manually also when changing the period/date. Also possible translations. This may then be breaking when doing it right, so another major version. Don't like that.

A possibility would be more to only use some cases which are well-known and easy (for example, last28 as in version 3.0 now by default) and as a fallback showing the configured "date"/"period" (without resolving the date). This can then be done better when really needed.

**Comment by brotkrueml** [comment]
@stigfaerch I added the display of date range for table widgets in main branch.

**Comment by brotkrueml** [comment]
Included with version 3.1.0.
